name: testcafe-testing-library
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    name: 'node ${{ matrix.node }} ${{matrix.browser}}  ${{ matrix.os }} '
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 10]
        browser: [chrome, firefox]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run validate
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: '${{ matrix.browser}} tests/testcafe'
