name: End-to-End Tests
on: [push, pull_request]

jobs:
  build:
    name: 'Run Tests on OS: ${{ matrix.os }} node version: ${{ matrix.node }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [10, 12]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - name: Start server
        run: npm run test:testcafe:serve
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: 'chrome tests/testcafe'
