name: End-to-End Tests
on: [push, pull_request]

jobs:
  build:
    name: '${{ matrix.os }} node ${{ matrix.node }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10, 12]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run test:unit
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          start: npm run test:testcafe:serve
          args: 'chrome tests/testcafe'
